version: "3.8"

services:
  jukoautomation_website:
    build: .
    image: jukoautomation-website:latest
    container_name: jukoautomation-website
    restart: unless-stopped
    ports:
      - "8082:80"   # Host 8082 → Container 80 (Nginx luistert hierop)
    healthcheck:
       test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - proxy

networks:
  proxy:
    external: true

